name: 'Manage support request issues'

on:
  issues:
    types: [ labeled, unlabeled, reopened ]

jobs:
  support:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/support-requests@v3
        with:
          github-token: ${{ github.token }}
          support-label: "Support request"
          issue-comment: >
            Hi, we only accept **bug reports** on this issue tracker, but this issue looks like a support request.


            Instead of creating an issue, try the following:

            - Ask the community on our [Discord server](https://discord.gg/R7kdetE)
            
            - Ask in the VRChat community [Discord server](https://discord.gg/vrchat)


            [Discord](https://discord.gg/R7kdetE) | [VRChat](https://discord.gg/vrchat)

          close-issue: true
          lock-issue: false